AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Monitoring Resources In AWS

Parameters:
  Identifier:
    Type: String
  Environment:
    Type: String

  SlackWebHookUrl:
    Type: String

  EmailAddress1:
    Type: String

  NotifyViaEmail:
    Type: String
    AllowedValues: ["True", "False"]
    Default: "False"

Conditions:
  IsProd: !Equals [!Ref Environment, "prod"]

Resources:

  NotificationStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./cw-resources/cw-template.yaml
      Parameters:
        Environment: !Ref Environment
        Identifier: !Ref Identifier
        EmailAddress: !Ref EmailAddress1

  ObserverLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "abfilms-shows-${Identifier}-${Environment}-observer/logs"
      RetentionInDays: !If [IsProd, 90, 7]

  StateMachineOberserverEmailNotifications:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "abfilms-${Identifier}-${Environment}-observer-topic"
      Subscription:
        - Endpoint: !Ref EmailAddress1
          Protocol: email

  StateMachineObserverFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "abfilms-${Identifier}-${Environment}-observer"
      LoggingConfig:
        LogGroup: !Ref ObserverLogGroup
      CodeUri: src/sfn-observer
      Handler: main.lambda_handler
      Runtime: python3.13
      Environment:
        Variables:
          SLACK_WEBHOOK_URL: !Sub "{{resolve:secretsmanager:${SlackWebHookUrl}:SecretString::AWSCURRENT}}"
          SNS_TOPIC_ARN: !Ref StateMachineOberserverEmailNotifications
          NOTIFY_VIA_EMAIL: !Ref NotifyViaEmail
      Policies:
        - CloudWatchPutMetricPolicy: {}
        - Statement:
          - Effect: Allow
            Action:
            - sns:Publish
            Resource: 
            - !Ref StateMachineOberserverEmailNotifications


  StateMachineEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Detects Step Functions Execution Status Changes"
      State: "ENABLED"
      EventPattern:
        source:
          - "aws.states"
        detail-type:
          - "Step Functions Execution Status Change"
      Targets:
        - Arn: !GetAtt StateMachineObserverFunction.Arn
          Id: "TargetLambdaV1"

  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref StateMachineObserverFunction
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt StateMachineEventRule.Arn


Outputs:

  AlarmFormatterLambdaArn:
    Description: "The ARN of the Lambda to set as the 'Action' in your CloudWatch Alarms"
    Value: !GetAtt NotificationStack.Outputs.AlarmFormatterLambdaArn