# srs.conf
listen              1935;
max_connections     1000;
srs_log_tank        console;
daemon              off;

http_api {
    enabled         on;
    listen          1985;
}

rtmp {
    listen              1935;
}

http_server {
    enabled         on;
    listen          8080;
}

vhost __defaultVhost__ {
    hls {
        enabled         on;
        hls_path        ./objs/nginx/html;
        hls_fragment    2;
        hls_window      60;
    }

    http_hooks {
        enabled         on;
        # Pointing to the 'srs-debug' service on port 3001
        on_publish      http://srs-debug:3001/on_publish;
        on_unpublish    http://srs-debug:3001/on_unpublish;
        on_play         http://srs-debug:3001/on_play;
        on_stop         http://srs-debug:3001/on_stop;
        on_connect      http://srs-debug:3001/on_connect;
    }
}