version: '3.8'

services:
  srs:
    image: ossrs/srs:6
    container_name: srs_server
    ports:
      - "1935:1935"   # RTMP Ingest
      - "1985:1985"   # HTTP API
      - "8080:8080"   # HTTP HLS Playback
    volumes:
      - ./srs-server/conf:/usr/local/srs/conf
      - ./srs-server/hls_segments:/usr/local/srs/objs/nginx/html
    restart: always

  srs-app:
    build: ./srs-debug
    container_name: srs_management_app
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    ports:
      - "3002:3001" # Host 3002 -> Container 3001
    restart: always
    volumes:
      - ./srs-server/hls_segments:/tmp/hls

  # s3-sidecar:
  #   build: ./srs-s3-sync
  #   container_name: srs_s3_sync
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./srs-server/hls_segments:/src:ro # Read-only mount of the HLS segments
  #   depends_on:
  #     - srs
  #   restart: always