region: "us-east-1"
identifier: "zexa-livego"

networking_config:
  enable: true
  cidr: 10.10.0.0/16
  public_subnet_cidrs: ["10.10.2.0/24", "10.10.3.0/24", "10.10.4.0/24"]
  private_subnet_cidrs: ["10.10.5.0/24", "10.10.6.0/24", "10.10.7.0/24"]

  security_groups:
    - name: server
      description: Live Go Server SG
      ingres:
        - from_port: -1
          to_port: -1
          protocol: -1
          description: Test Rule
          cidr_blocks: 190.148.209.58/32 ## MY LOCAL IP
      egress:
        - from_port: -1
          to_port: -1
          protocol: -1
          description: Allow All Out
          cidr_blocks: 0.0.0.0/0
s3_hls:
  hls_retention_days: 7
  recording_retention_days: 60
  cors_origins: 
    - "*"

server_config:
  volume_size: 20
  volume_type: "gp3"
  monitoring_enabled: true
  max_instances: 1
  min_instances: 1
  instance_type: "t3.large"
  user_data:
    package_update: true
    package_upgrade: true
    packages:
      - docker
    runcmd:
      - sudo curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
      - sudo unzip -q /tmp/awscliv2.zip -d /tmp
      - sudo /tmp/aws/install --update
      - sudo rm -rf /tmp/aws /tmp/awscliv2.zip
      - sudo systemctl start docker
      - docker run --name zexa-livego -p 1935:1935 -p 7001:7001 -p 7002:7002 -p 8090:8090 -d gwuhaolin/livego

tags: 
  Project: LiveGoServer