region: "us-east-1"
identifier: "zexa-livego"

networking_config:
  enable: true
  cidr: 10.10.0.0/16
  public_subnet_cidrs: ["10.10.2.0/24", "10.10.3.0/24", "10.10.4.0/24"]
  private_subnet_cidrs: ["10.10.5.0/24", "10.10.6.0/24", "10.10.7.0/24"]

  security_groups:
    - name: server
      description: Live Go Server SG
      ingres:
        - from_port: -1
          to_port: -1
          protocol: -1
          description: Test Rule
          cidr_blocks: 181.189.154.125/32 ## MY LOCAL IP
      egress:
        - from_port: -1
          to_port: -1
          protocol: -1
          description: Allow All Out
          cidr_blocks: 0.0.0.0/0
s3_hls:
  hls_retention_days: 7
  recording_retention_days: 60
  cors_origins: 
    - "*"

server_config:
  volume_size: 20
  volume_type: "gp3"
  monitoring_enabled: true
  max_instances: 0
  min_instances: 0
  instance_type: "t3.large"
  user_data:
    package_update: true
    package_upgrade: true
    write_files:
      - path: /opt/livego/docker-compose.yml
        owner: root:root
        permissions: '0644'
        content: |
          version: '3.8'
          services:
            livego:
              image: gwuhaolin/livego
              container_name: livego_server
              restart: always
              ports:
                - "1935:1935"
                - "8090:8090"
                - "7001:7001"
                - "7002:7002"
              logging:
                driver: "json-file"
                options:
                  max-size: "10m"
                  max-file: "3"
    packages:
      - docker
    runcmd:
      - sudo curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
      - sudo unzip -q /tmp/awscliv2.zip -d /tmp
      - sudo /tmp/aws/install --update
      - sudo rm -rf /tmp/aws /tmp/awscliv2.zip
      - sudo systemctl start docker
      - sudo mkdir -p /usr/libexec/docker/cli-plugins && sudo curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-$(uname -m) -o /usr/libexec/docker/cli-plugins/docker-compose
      - sudo chmod +x /usr/libexec/docker/cli-plugins/docker-compose
      - sudo /usr/libexec/docker/cli-plugins/docker-compose --version
      - cd /opt/livego && /usr/libexec/docker/cli-plugins/docker-compose up -d

tags: 
  Project: LiveGoServer