AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Project to deploy mediaconvert resources

Parameters:

  Identifier:
    Description: name added to resources
    Type: String

  Environment:
    Description: name
    Type: String

  QueuesStatus:
    Description: queues status setup
    Type: String

  DRMTodayApiResourceArn:
    Description: DRMToday Integration API Arn
    Type: String
    Default: ""

Conditions:
  IsDev: !Equals [!Ref Environment, "dev"]
  CreateDRMPolicy: !Not [!Equals [!Ref DRMTodayApiResourceArn, ""]]

Resources:

  DRMTodayInvokePolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: CreateDRMPolicy
    Properties:
      ManagedPolicyName: !Sub "abfilms-${Identifier}-${Environment}-drmtoday-invoke-policy"
      Description: "Policy to allow invoking the DRMToday API"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "execute-api:Invoke"
            Resource: !Ref DRMTodayApiResourceArn

  MediaConvertRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "abfilms-${AWS::Region}-${Identifier}-${Environment}-mediaconvert-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: mediaconvert.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchEventsFullAccess
        - !If [CreateDRMPolicy, !Ref DRMTodayInvokePolicy, !Ref "AWS::NoValue"]
      Policies:
        - PolicyName: MediaConvertS3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # 1. Permission to read source files (MP4, SRT)
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetBucketLocation
                Resource: 
                  - '*'
              
              # 2. Permission to write HLS outputs
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource: 
                  - '*'

  MediaConvertQueues:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./mediaconvert/queues.yaml
      Parameters:
        Identifier: !Ref Identifier
        Environment: !Ref Environment
        QueuesStatus: !Ref QueuesStatus

  MediaConvertTemplates:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./mediaconvert/templates.yaml
      Parameters:
        Identifier: !Ref Identifier
        Environment: !Ref Environment

Outputs:

  MoviesJobTemplate:
    Value: !GetAtt MediaConvertTemplates.Outputs.MoviesJobTemplate
    Export:
      Name: MoviesJobTemplate

  ShowsJobTemplate:
    Value: !GetAtt MediaConvertTemplates.Outputs.ShowsJobTemplate
    Export:
      Name: ShowsJobTemplate

  MovieQueueArn:
    Value: !GetAtt MediaConvertQueues.Outputs.MovieQueueArn
    Export:
      Name: MovieQueueArn

  ShowQueueArn:
    Value: !GetAtt MediaConvertQueues.Outputs.ShowQueueArn
    Export:
      Name: ShowQueueArn

  MediaConvertRoleArn:
    Value: !GetAtt MediaConvertRole.Arn
    Export:
      Name: MediaConvertRoleArn