AWSTemplateFormatVersion: '2010-09-09'
Description: Creates an AWS Backup Vault and a new KMS key (shared with the Organization) to encrypt it.

Parameters:

  Environment:
    Type: String
    Description: The environment (e.g., Dev, Stage, Prod) for resource tagging.
    Default: Dev
    AllowedValues:
      - Dev
      - Stage
      - Prod

  OrganizationId:
    Type: String
    Description: Your AWS Organization ID (e.g., o-xxxxxxxxxx).
    AllowedPattern: '^o-[a-z0-9]{10,32}$'
    ConstraintDescription: Must be a valid AWS Organization ID.

  Identifier:
    Type: String
    Description: adding resources identifiers

  # New parameters for the Copy Logic
  SecondaryVaultArn:
    Type: String
    Description: The ARN of the destination vault where backups should be copied upon completion.
    Default: ""

  BackupServiceRoleArn:
    Type: String
    Description: The ARN of the IAM Role that AWS Backup should use to perform the copy.

  EnableCopyTrigger:
    Type: String
    Description: Set to 'true' to enable automatic copying of completed backups.
    Default: "false"
    AllowedValues:
      - "true"
      - "false"

  DestinationRetentionDays:
    Type: Number
    Description: The number of days to retain the backup copy in the secondary vault.
    Default: 30

Resources:

  KmsKeyForBackup:
    Type: AWS::KMS::Key
    Properties:
      Description: !Sub 'KMS key for encrypting ${Environment} AWS Backup vaults, shareable across the organization'
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          # Statement 1: Allows full control for the root user of this account
          - Sid: AllowFullControlForRoot
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'

          # Statement 2: Allows AWS Backup to use the key
          - Sid: AllowBackupService
            Effect: Allow
            Principal:
              Service: backup.amazonaws.com
            Action:
              - 'kms:*'
            Resource: '*'

          # Statement 3: Allows all principals in your AWS Organization to use the key for crypto operations
          - Sid: AllowCryptoUseForOrganization
            Effect: Allow
            Principal:
              AWS: '*'
            Action:
              - 'kms:*'
            Resource: '*'
            Condition:
              StringEquals:
                'aws:PrincipalOrgID': !Ref OrganizationId
      
      EnableKeyRotation: false
      Tags:
        - Key: Name
          Value: !Sub '${Identifier}-backup-kms-key-${Environment}'
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: 'AWS Backup Encryption'

  KmsKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub 'alias/aws-backup-key-${Identifier}-${Environment}'
      TargetKeyId: !Ref KmsKeyForBackup

  EncryptedBackupVault:
    Type: AWS::Backup::BackupVault
    Properties:
      BackupVaultName: !Sub '${Identifier}-backup-vault-${Environment}'
      # Reference the ARN of the KMS key created in this template
      EncryptionKeyArn: !GetAtt KmsKeyForBackup.Arn
      AccessPolicy:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::137708847303:role/CustomBackupServiceRole' # giving access to the role in the AUDIT account
            Action: 'backup:CopyIntoBackupVault'
            Resource: "*"

  # ---------------------------------------------------------
  # Lambda Logger Resources
  # ---------------------------------------------------------

  BackupLoggerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      # Added inline policy to allow the Lambda to trigger AWS Backup copy jobs
      Policies:
        - PolicyName: AllowBackupCopyTrigger
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: backup:StartCopyJob
                Resource: "*"
              - Effect: Allow
                Action: iam:PassRole
                Resource: !Ref BackupServiceRoleArn

  BackupLoggerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${Identifier}-backup-logger-${Environment}'
      Handler: index.handler
      Role: !GetAtt BackupLoggerRole.Arn
      Runtime: python3.9
      Timeout: 30
      Environment:
        Variables:
          SECONDARY_VAULT_ARN: !Ref SecondaryVaultArn
          BACKUP_SERVICE_ROLE_ARN: !Ref BackupServiceRoleArn
          ENABLE_COPY_TRIGGER: !Ref EnableCopyTrigger
          DESTINATION_RETENTION_DAYS: !Ref DestinationRetentionDays
      Code:
        ZipFile: |
          import json
          import logging
          import os
          import boto3

          logger = logging.getLogger()
          logger.setLevel(logging.INFO)
          backup_client = boto3.client('backup')

          def handler(event, context):
              # 1. Log the incoming event
              print("BACKUP_EVENT: " + json.dumps(event))

  BackupLoggerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref BackupLoggerFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt BackupVaultMonitorRule.Arn

  BackupVaultMonitorRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub '${Identifier}-backup-monitor-rule-${Environment}'
      Description: "Detects all AWS Backup events (any state) for this specific vault."
      EventPattern:
        source:
          - aws.backup
        detail-type:
          - "Backup Job State Change"
          # - "Restore Job State Change"
          - "Recovery Point State Change"
          - "Copy Job State Change"
        detail:
          # Removed specific 'state' filter to catch ALL states (CREATED, RUNNING, COMPLETED, FAILED, etc.)
          backupVaultArn:
            - !GetAtt EncryptedBackupVault.BackupVaultArn
      Targets:
        - Arn: !GetAtt BackupLoggerFunction.Arn
          Id: "BackupLoggerTarget"

Outputs:

  BackupVaultName:
    Description: The name of the created Backup Vault.
    Value: !Ref EncryptedBackupVault
  
  BackupVaultArn:
    Description: The ARN of the created Backup Vault.
    Value: !GetAtt EncryptedBackupVault.BackupVaultArn

  KmsKeyId:
    Description: The ID of the KMS key
    Value: !Ref KmsKeyForBackup
  
  KmsKeyArn:
    Description: The ARN of the KMS key
    Value: !GetAtt KmsKeyForBackup.Arn

  KmsKeyAliasName:
    Description: The alias of the KMS key
    Value: !Ref KmsKeyAlias