AWSTemplateFormatVersion: '2010-09-09'
Description: Creates an AWS Backup Vault, KMS Key, and EventBridge monitoring that triggers a cross-region Lambda on copy completion.

Parameters:

  Environment:
    Type: String
    Description: The environment (e.g., Dev, Stage, Prod) for resource tagging.
    Default: Dev
    AllowedValues:
      - Dev
      - Stage
      - Prod

  OrganizationId:
    Type: String
    Description: Your AWS Organization ID (e.g., o-xxxxxxxxxx).
    AllowedPattern: '^o-[a-z0-9]{10,32}$'
    ConstraintDescription: Must be a valid AWS Organization ID.

  Identifier:
    Type: String
    Description: adding resources identifiers

  # New parameters for Cross-Region Lambda Trigger
  # TargetLambdaArn:
  #   Type: String
  #   Description: The ARN of the Lambda function in the other region that receives the copy job data.

  TargetRegion:
    Type: String
    Default: "us-east-1"
    Description: The AWS Region where the target Lambda is located (e.g., us-west-2).

Resources:

  KmsKeyForBackup:
    Type: AWS::KMS::Key
    Properties:
      Description: !Sub 'KMS key for encrypting ${Environment} AWS Backup vaults, shareable across the organization'
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          # Statement 1: Allows full control for the root user of this account
          - Sid: AllowFullControlForRoot
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'

          # Statement 2: Allows AWS Backup to use the key
          - Sid: AllowBackupService
            Effect: Allow
            Principal:
              Service: backup.amazonaws.com
            Action:
              - 'kms:*'
            Resource: '*'

          # Statement 3: Allows all principals in your AWS Organization to use the key for crypto operations
          - Sid: AllowCryptoUseForOrganization
            Effect: Allow
            Principal:
              AWS: '*'
            Action:
              - 'kms:*'
            Resource: '*'
            Condition:
              StringEquals:
                'aws:PrincipalOrgID': !Ref OrganizationId
      
      EnableKeyRotation: false
      Tags:
        - Key: Name
          Value: !Sub '${Identifier}-backup-kms-key-${Environment}'
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: 'AWS Backup Encryption'

  KmsKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub 'alias/aws-backup-key-${Environment}'
      TargetKeyId: !Ref KmsKeyForBackup

  EncryptedBackupVault:
    Type: AWS::Backup::BackupVault
    Properties:
      BackupVaultName: !Sub '${Identifier}-backup-vault-${Environment}'
      # Reference the ARN of the KMS key created in this template
      EncryptionKeyArn: !GetAtt KmsKeyForBackup.Arn
      AccessPolicy:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::137708847303:role/CustomBackupServiceRole' # giving access to the role in the AUDIT account
            Action: 'backup:CopyIntoBackupVault'
            Resource: "*"

  # ---------------------------------------------------------
  # Lambda Forwarder Resources
  # ---------------------------------------------------------

  BackupLoggerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      # Added inline policy to allow the Lambda to invoke the remote function
      Policies:
        - PolicyName: AllowRemoteLambdaInvoke
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource: !Sub "arn:aws:lambda:${TargetRegion}:${AWS::AccountId}:function:intermediate-backup-logger-${Environment}"

  BackupLoggerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${Identifier}-backup-logger-${Environment}'
      Handler: index.handler
      Role: !GetAtt BackupLoggerRole.Arn
      Runtime: python3.9
      Timeout: 30
      Environment:
        Variables:
          TARGET_LAMBDA_ARN: !Sub "arn:aws:lambda:${TargetRegion}:${AWS::AccountId}:function:intermediate-backup-logger-${Environment}"
          TARGET_REGION: !Ref TargetRegion
      Code:
        ZipFile: |
          import json
          import logging
          import os
          import boto3

          logger = logging.getLogger()
          logger.setLevel(logging.INFO)

          def handler(event, context):
              # 1. Log the incoming event
              print("RECEIVED_EVENT: " + json.dumps(event))

              # 2. Initialize Client for Target Region
              target_region = os.environ.get('TARGET_REGION')
              target_arn = os.environ.get('TARGET_LAMBDA_ARN')
              
              if not (target_region and target_arn):
                  logger.error("Missing TARGET_REGION or TARGET_LAMBDA_ARN environment variables.")
                  return {'statusCode': 500, 'body': 'Configuration Error'}

              lambda_client = boto3.client('lambda', region_name=target_region)

              # 3. Check for specific event type (Copy Job Completed)
              detail = event.get('detail', {})
              detail_type = event.get('detail-type')
              state = detail.get('state')
              
              # We only want to trigger the remote lambda if a Copy Job successfully landed in this vault
              if detail_type == "Copy Job State Change" and state == 'COMPLETED':
                  logger.info(f"Copy Job Completed. Invoking remote lambda: {target_arn} in {target_region}")
                  
                  try:
                      # Invoke the remote lambda asynchronously (Event type)
                      response = lambda_client.invoke(
                          FunctionName=target_arn,
                          InvocationType='Event',
                          Payload=json.dumps(event)
                      )
                      logger.info(f"Remote invocation initiated. Status Code: {response['StatusCode']}")
                      return {'statusCode': 200, 'body': 'Remote Lambda Invoked'}
                      
                  except Exception as e:
                      logger.error(f"Failed to invoke remote lambda: {str(e)}")
                      raise e
              
              else:
                  logger.info("Event is not a completed Copy Job. Skipping remote invocation.")
                  return {'statusCode': 200, 'body': 'Skipped'}

  # New Rule: Detects incoming Copy Jobs that land in this vault
  BackupVaultCopyMonitorRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub '${Identifier}-copy-monitor-rule-${Environment}'
      Description: "Detects Copy Jobs where this vault is the destination."
      EventPattern:
        source:
          - aws.backup
        detail-type:
          - "Copy Job State Change"
        # detail:
        #   # For copies, we must check the DESTINATION vault ARN, not the source
        #   destinationBackupVaultArn:
        #     - !GetAtt EncryptedBackupVault.BackupVaultArn
      Targets:
        - Arn: !GetAtt BackupLoggerFunction.Arn
          Id: "BackupLoggerTarget"

  # Permission for the new Copy Monitor Rule to invoke the Lambda
  BackupCopyLoggerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref BackupLoggerFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt BackupVaultCopyMonitorRule.Arn

Outputs:

  BackupVaultName:
    Description: The name of the created Backup Vault.
    Value: !Ref EncryptedBackupVault
  
  BackupVaultArn:
    Description: The ARN of the created Backup Vault.
    Value: !GetAtt EncryptedBackupVault.BackupVaultArn

  KmsKeyId:
    Description: The ID of the KMS key
    Value: !Ref KmsKeyForBackup
  
  KmsKeyArn:
    Description: The ARN of the KMS key
    Value: !GetAtt KmsKeyForBackup.Arn

  KmsKeyAliasName:
    Description: The alias of the KMS key
    Value: !Ref KmsKeyAlias