AWSTemplateFormatVersion: '2010-09-09'
Description: Creates an AWS Backup Vault and a new KMS key (shared with the Organization) to encrypt it.

Parameters:

  Environment:
    Type: String
    Description: The environment (e.g., Dev, Stage, Prod) for resource tagging.
    Default: Dev
    AllowedValues:
      - Dev
      - Stage
      - Prod

  OrganizationId:
    Type: String
    Description: Your AWS Organization ID (e.g., o-xxxxxxxxxx).
    AllowedPattern: '^o-[a-z0-9]{10,32}$'
    ConstraintDescription: Must be a valid AWS Organization ID.

  Identifier:
    Type: String
    Description: adding resources identifiers

Resources:

  KmsKeyForBackup:
    Type: AWS::KMS::Key
    Properties:
      Description: !Sub 'KMS key for encrypting ${Environment} AWS Backup vaults, shareable across the organization'
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          # Statement 1: Allows full control for the root user of this account
          - Sid: AllowFullControlForRoot
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'

          # Statement 2: Allows AWS Backup to use the key
          - Sid: AllowBackupService
            Effect: Allow
            Principal:
              Service: backup.amazonaws.com
            Action:
              - 'kms:DescribeKey'
              - 'kms:Encrypt'
              - 'kms:Decrypt'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey*'
              - 'kms:CreateGrant'
            Resource: '*'

          # Statement 3: Allows all principals in your AWS Organization to use the key for crypto operations
          - Sid: AllowCryptoUseForOrganization
            Effect: Allow
            Principal:
              AWS: '*'
            Action:
              - 'kms:*'
            Resource: '*'
            Condition:
              StringEquals:
                'aws:PrincipalOrgID': !Ref OrganizationId
      
      EnableKeyRotation: false
      Tags:
        - Key: Name
          Value: !Sub '${Identifier}-backup-kms-key-${Environment}'
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: 'AWS Backup Encryption'

  KmsKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub 'alias/aws-backup-key-${Environment}'
      TargetKeyId: !Ref KmsKeyForBackup

  EncryptedBackupVault:
    Type: AWS::Backup::BackupVault
    Properties:
      BackupVaultName: !Sub '${Identifier}-backup-vault-${Environment}'
      # Reference the ARN of the KMS key created in this template
      EncryptionKeyArn: !GetAtt KmsKeyForBackup.Arn
      AccessPolicy:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::137708847303:role/CustomBackupServiceRole' # giving access to the role in the AUDIT account
            Action: 'backup:CopyIntoBackupVault'
            Resource: "*"

Outputs:

  BackupVaultName:
    Description: The name of the created Backup Vault.
    Value: !Ref EncryptedBackupVault
  
  BackupVaultArn:
    Description: The ARN of the created Backup Vault.
    Value: !GetAtt EncryptedBackupVault.BackupVaultArn

  KmsKeyId:
    Description: The ID of the KMS key
    Value: !Ref KmsKeyForBackup
  
  KmsKeyArn:
    Description: The ARN of the KMS key
    Value: !GetAtt KmsKeyForBackup.Arn

  KmsKeyAliasName:
    Description: The alias of the KMS key
    Value: !Ref KmsKeyAlias